In [3]:
import pandas as pd
import random
from faker import Faker

In [4]:
fake = Faker()
customers = [] #this initializes fake data generator

In [10]:
for i in range(1,10001):
    customers.append([
        i,
        fake.name(),
        random.choice(['Male','Female']),
        random.randint(18,70),
        fake.city(),
        fake.state(),
        fake.date_between(start_date='-5y',end_date='today')
    ])
        
#Creates 10,000 customers
#Each customer has:
#ID,Name,Gender,Age,City,State,Join Date

In [11]:
customers_df = pd.DataFrame(customers, columns=[
    'customer_id',
    'customer_name',
    'gender',
    'age',
    'city',
    'state',
    'join_date'
])
#This converts data into table form.

In [12]:
customers_df.head()

,customer_id,customer_name,gender,age,city,state,join_date
0,1,Sarah Peterson,Male,64,North Johntown,California,2024-05-24
1,2,Valerie Cruz,Male,61,East Anafurt,Wyoming,2022-05-25
2,3,Stephanie Marshall,Male,39,Derrickside,Colorado,2024-09-16
3,4,Kristie Yu,Female,44,West Johnberg,North Dakota,2023-03-11
4,5,Daniel Phillips,Male,30,Lake Christine,Alabama,2022-09-20

In [13]:
customers_df.head(10)

,customer_id,customer_name,gender,age,city,state,join_date
0,1,Sarah Peterson,Male,64,North Johntown,California,2024-05-24
1,2,Valerie Cruz,Male,61,East Anafurt,Wyoming,2022-05-25
2,3,Stephanie Marshall,Male,39,Derrickside,Colorado,2024-09-16
3,4,Kristie Yu,Female,44,West Johnberg,North Dakota,2023-03-11
4,5,Daniel Phillips,Male,30,Lake Christine,Alabama,2022-09-20
5,6,Evelyn Williams,Female,27,Nicholasstad,New Jersey,2026-06-27
6,7,Angela Johnson,Female,39,Martinezmouth,Utah,2023-07-04
7,8,Katrina Martinez,Female,64,North Samantha,Alaska,2025-12-02
8,9,Michelle Ali,Male,32,New Melindaville,Wyoming,2022-09-02
9,10,Jacqueline Braun,Male,51,Martinshire,Mississippi,2025-09-30

In [15]:
customers_df.to_csv("customers.csv", index=False)

In [ ]:
#

In [4]:
import random
import pandas as pd
import random
from faker import Faker

fake = Faker()
product = []
categories = {
    'Electronics':['Mobile','Laptop','TV'],
    'Fashion': ['Shirt', 'Shoes', 'Jeans'],
    'Grocery': ['Snacks', 'Beverages', 'Dairy'],
    'Home': ['Furniture', 'Decor', 'Kitchen']
}
brands = ['Samsung', 'Nike', 'Apple', 'Sony', 'Adidas', 'LG', 'Puma']
for i in range(1, 501):
    category = random.choice(list(categories.keys()))
    sub_category = random.choice(categories[category])

    cost = random.randint(100, 5000)
    selling = cost + random.randint(50, 2000)

    product.append([
        i,
        fake.word().capitalize(),
        category,
        sub_category,
        random.choice(brands),
        cost,
        selling
    ])

In [7]:
product_df = pd.DataFrame(product, columns=[
    'product_id',
    'product_name',
    'category',
    'sub_category',
    'brand',
    'cost_price',
    'selling_price'
])

In [8]:
product_df.head()

,product_id,product_name,category,sub_category,brand,cost_price,selling_price
0,1,Detail,Grocery,Snacks,Apple,4619,5637
1,2,Listen,Electronics,Laptop,Apple,1885,1985
2,3,Form,Grocery,Beverages,Adidas,1932,2953
3,4,Parent,Fashion,Shirt,Apple,4675,4757
4,5,Administration,Fashion,Shoes,Nike,2676,4091

In [9]:
product_df.to_csv("product.csv", index=False)

In [14]:
import random
import pandas as pd
from faker import Faker

fake = Faker()
stores = []

for i in range(1, 51):
    stores.append([
        i,
        f"Store_{i}",
        fake.city(),
        fake.state(),
        fake.name()
    ])

In [11]:
stores_df = pd.DataFrame(stores, columns=[
    'store_id',
    'store_name',
    'city',
    'state',
    'manager_name'
])

In [12]:
stores_df.head()

   store_id store_name           city         state       manager_name
0         1    Store_1  Port Coryside        Hawaii     James Anderson
1         2    Store_2      Paulhaven      Oklahoma     Jocelyn Taylor
2         3    Store_3    Lake Ashley      Virginia  Jonathan Griffith
3         4    Store_4    Lake Denise  Rhode Island        Mary Potter
4         5    Store_5      Mccoyview      Virginia    Jessica Mcguire

In [13]:
stores_df.to_csv("stores.csv", index=False)

In [16]:
import random
import pandas as pd
from faker import Faker
orders = []

payment_methods = ['Cash', 'Card', 'UPI', 'Net Banking']

for i in range(1, 50001):
    orders.append([
        i,
        random.randint(1, 10000),   # customer_id
        random.randint(1, 50),      # store_id
        fake.date_between(start_date='-2y', end_date='today'),
        random.choice(payment_methods)
    ])

In [17]:
orders_df = pd.DataFrame(orders, columns=[
    'order_id',
    'customer_id',
    'store_id',
    'order_date',
    'payment_method'
])

In [18]:
orders_df.head()

   order_id  customer_id  store_id  order_date payment_method
0         1         8748        27  2025-06-11           Cash
1         2         8775         7  2025-08-17            UPI
2         3         7223        15  2025-05-05    Net Banking
3         4         2391        18  2025-12-15           Card
4         5         2603        34  2024-09-23    Net Banking

In [19]:
orders_df.to_csv("orders.csv", index=False)

In [20]:
import random
import pandas as pd
from faker import Faker
order_details = []

for i in range(1, 100001):
    order_details.append([
        i,
        random.randint(1, 50000),   # order_id
        random.randint(1, 500),     # product_id
        random.randint(1, 10),      # quantity
        round(random.uniform(0, 30), 2)   # discount %
    ])

In [21]:
order_details_df = pd.DataFrame(order_details, columns=[
    'order_detail_id',
    'order_id',
    'product_id',
    'quantity',
    'discount'
])

In [22]:
order_details_df.head()

   order_detail_id  order_id  product_id  quantity  discount
0                1      8131         129         1      3.74
1                2     16212         198         4     20.97
2                3     12469         350         8     18.12
3                4     16219         377         7     17.14
4                5     15092         371         1     13.29

In [23]:
order_details_df.to_csv("order_details.csv", index=False)

In [1]:
import pandas as pd

df = pd.read_csv("order_details.csv")

print(df.head(10))

   order_detail_id  order_id  product_id  quantity  discount
0                1      8131         129         1      3.74
1                2     16212         198         4     20.97
2                3     12469         350         8     18.12
3                4     16219         377         7     17.14
4                5     15092         371         1     13.29
5                6     10255         448         7      1.09
6                7     24080         192         6     16.53
7                8     33596         221         5     17.13
8                9     11295         188         2     16.79
9               10     49386         389         5     29.63

In [2]:
print(df['order_detail_id'].duplicated().sum())

0

In [4]:
orders = pd.read_csv("orders.csv")

invalid = df[~df['order_id'].isin(orders['order_id'])]

print(invalid.head())
print("Invalid rows:", len(invalid))

Empty DataFrame
Columns: [order_detail_id, order_id, product_id, quantity, discount]
Index: []
Invalid rows: 0

In [5]:
orders = pd.read_csv("orders.csv")
order_details = pd.read_csv("order_details.csv")

missing = order_details[~order_details['order_id'].isin(orders['order_id'])]

print(missing.head(20))
print("Missing:", len(missing))

Empty DataFrame
Columns: [order_detail_id, order_id, product_id, quantity, discount]
Index: []
Missing: 0